### ISSUE TITLE
DSDT Patch for LED light

### ISSUE THREAD

**Issue by rajesheber** [shmilee/T450-Hackintosh#1]
I am installing El Capitan on T450. Have got most of them working except Wifi/BT which needs the card to be replaced. I have an issue where the Power LED keeps blinking after waking up from sleep. Would you be aware of the DSDT patch to be applied for this.

**Comment by shmilee** [comment]
Have you tried this(No idea how to write it in a dsdt patch):
https://github.com/shmilee/T450-Hackintosh/blob/master/Install-10.10.5.rst#dsdt-wake-fix
After wake up from sleep, power led and red dot light continute to blink. We can fix this by adding these lines into method _WAK after NVSS: (Ref: Ludacrisvp's t440s guide)

```
\_SB.PCI0.LPC.EC.LED (0x00, 0x80)
\_SB.PCI0.LPC.EC.LED (0x0A, 0x80)
```

After adding that, it will look like this:

```
If (LEqual (Arg0, 0x03))
{
    NVSS (0x00)
    \_SB.PCI0.LPC.EC.LED (0x00, 0x80)
    \_SB.PCI0.LPC.EC.LED (0x0A, 0x80)
    Store (\_SB.PCI0.LPC.EC.AC._PSR (), PWRS)
    If (OSC4)
    {
        PNTF (0x81)
    }
```

https://github.com/shmilee/T450-Hackintosh/blob/master/DSDT/Patched/2-wake-DSDT.dsl#L14894

**Comment by rajesheber** [comment]
Thank you for the response. I did add the same method and was resolved. I wanted to know how you can enable twin battery status on the battery icon on the status bar. What DSDT patc would you apply.

Raj 

Date: Wed, 21 Oct 2015 21:10:08 -0700

**Comment by shmilee** [comment]
Twin battery status? 
What I did about the battery is [here](https://github.com/shmilee/T450-Hackintosh/blob/master/Install-10.10.5.rst#dsdt-battery-status),  which only enables one battery. Maybe you can read [the battery status guide](http://www.tonymacx86.com/el-capitan-laptop-support/116102-guide-how-patch-dsdt-working-battery-status.html), and some [examples](https://github.com/RehabMan/Laptop-DSDT-Patch/tree/master/battery) to help you.

**Comment by rajesheber** [comment]
Yes my T450 has two batteries so wanted to know how to fix it

Rajesh Eber

**Comment by polarlights** [comment]
@rajesheber  Dual batteries support was removed since yosemite. My laptop is T450s with dual batteries. Now it can show the percentage one by one. Maybe merging two batteries together in DSDT is possible. But I think we can ignore it right now. If you have solved this, please let me know. Enjoy!
