### ISSUE TITLE
Display distorted on reboot with Lid closed

### ISSUE THREAD

**Issue by rajesheber** [shmilee/T450-Hackintosh#11]
Hi,
   I have been able to get all of the functions working on my T450 on Elcapitan but when i reboot the machine connected to an external HDMI monitor connected to my DP with the lid closed on resuming to the desktop the desktop is distorted and have to force reboot with lid open for a usable desktop. Have you tested and solution that you share here with me.

**Comment by shmilee** [comment]
Test with an external DP monitor：
Before the lid closed
![2016-03-28 4 20 13](https://cloud.githubusercontent.com/assets/2681740/14074208/e7c8e978-f501-11e5-8c29-a28333a4f11f.png)
then
![2016-03-28 4 21 34](https://cloud.githubusercontent.com/assets/2681740/14074232/1251b97c-f502-11e5-9b01-7a81c60c1357.png)

While closing the lid，M92Z monitor is distorted only for a second. After that, all works fine.

I guess your problem  is related to high resolution. 

bigger than 1920x1080?

**Comment by rajesheber** [comment]
Did you try to reboot with lid closed and connected to external monitor.

Raj

**Comment by shmilee** [comment]
Yes, I tried.
Close lid, reboot. Then grub --> clover --> osx login --> osx desktop, all of them are displayed on external monitor (M92z).

**Comment by rajesheber** [comment]
Once you reach the desktop if you open the lid do you see both the displays with desktop . Mine reboots when the lid is opened.

Raj

**Comment by shmilee** [comment]
Can‘t see both, system crashes and reboots.

```
*** Panic Report ***
panic(cpu 0 caller 0xffffff7f994baf3d): assertmsg@/Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-10.14.58/Common/IONDRV/Intel/BDW/AppleIntelFramebuffer/AppleIntelController.cpp:21145
Backtrace (CPU 0), Frame : Return Address
0xffffff9125d9b710 : 0xffffff80170dab12 
0xffffff9125d9b790 : 0xffffff7f994baf3d 
0xffffff9125d9b7c0 : 0xffffff7f994a7bf1 
0xffffff9125d9b7e0 : 0xffffff7f994a7499 
0xffffff9125d9bbb0 : 0xffffff7f9823fba1 
0xffffff9125d9bbe0 : 0xffffff80176df277 
0xffffff9125d9bd20 : 0xffffff8017197cc0 
0xffffff9125d9be30 : 0xffffff80170df283 
0xffffff9125d9be60 : 0xffffff80170c28b8 
0xffffff9125d9bea0 : 0xffffff80170d2665 
0xffffff9125d9bf10 : 0xffffff80171b8bda 
0xffffff9125d9bfb0 : 0xffffff80171eca96 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOGraphicsFamily(2.4.1)[172C2960-EDF5-382D-80A5-C13E97D74880]@0xffffff7f9822b000->0xffffff7f98265fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[4FE41F9B-2849-322A-BBF8-A94816C003D6]@0xffffff7f9791d000
         com.apple.driver.AppleIntelBDWGraphicsFramebuffer(10.1.4)[2D97D8DD-0D3B-382C-A884-B59E40981DF3]@0xffffff7f9949a000->0xffffff7f994effff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[4FE41F9B-2849-322A-BBF8-A94816C003D6]@0xffffff7f9791d000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[5D7574C3-8E90-3873-BAEB-D979FC215A7D]@0xffffff7f98080000
            dependency: com.apple.iokit.IOAcceleratorFamily2(205.3)[1B6944F0-F0F4-3D26-892C-46EB6C5C7433]@0xffffff7f99419000
            dependency: com.apple.iokit.IOReportFamily(31)[C89107EE-2DF2-3BC3-9F6D-3133D43ED7EF]@0xffffff7f98baf000
            dependency: com.apple.AppleGraphicsDeviceControl(3.12.6)[F211EB28-182A-34BB-A610-87667618F925]@0xffffff7f99493000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[172C2960-EDF5-382D-80A5-C13E97D74880]@0xffffff7f9822b000

BSD process name corresponding to current thread: WindowServer
Boot args: kext-dev-mode=1 dart=0 -gux_defer_usb2 nv_disable=1 rootless=0  

Mac OS version:
15E65
```

**Comment by rajesheber** [comment]
Thanx for the log trace. Any clues how to resolve this. What SMBIOS model your using.

Rajesh Eber

On 30-Mar-2016, at 5:32 PM, shmilee <notifications@github.com<mailto:notifications@github.com>> wrote:

Can't see both, system crashes and reboots.

**\* Panic Report ***
panic(cpu 0 caller 0xffffff7f994baf3d): assertmsg@/Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-10.14.58/Common/IONDRV/Intel/BDW/AppleIntelFramebuffer/AppleIntelController.cpp:21145
Backtrace (CPU 0), Frame : Return Address
0xffffff9125d9b710 : 0xffffff80170dab12
0xffffff9125d9b790 : 0xffffff7f994baf3d
0xffffff9125d9b7c0 : 0xffffff7f994a7bf1
0xffffff9125d9b7e0 : 0xffffff7f994a7499
0xffffff9125d9bbb0 : 0xffffff7f9823fba1
0xffffff9125d9bbe0 : 0xffffff80176df277
0xffffff9125d9bd20 : 0xffffff8017197cc0
0xffffff9125d9be30 : 0xffffff80170df283
0xffffff9125d9be60 : 0xffffff80170c28b8
0xffffff9125d9bea0 : 0xffffff80170d2665
0xffffff9125d9bf10 : 0xffffff80171b8bda
0xffffff9125d9bfb0 : 0xffffff80171eca96
      Kernel Extensions in backtrace:
         com.apple.iokit.IOGraphicsFamily(2.4.1)[172C2960-EDF5-382D-80A5-C13E97D74880]@0xffffff7f9822b000->0xffffff7f98265fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[4FE41F9B-2849-322A-BBF8-A94816C003D6]@0xffffff7f9791d000
         com.apple.driver.AppleIntelBDWGraphicsFramebuffer(10.1.4)[2D97D8DD-0D3B-382C-A884-B59E40981DF3]@0xffffff7f9949a000->0xffffff7f994effff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[4FE41F9B-2849-322A-BBF8-A94816C003D6]@0xffffff7f9791d000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[5D7574C3-8E90-3873-BAEB-D979FC215A7D]@0xffffff7f98080000
            dependency: com.apple.iokit.IOAcceleratorFamily2(205.3)[1B6944F0-F0F4-3D26-892C-46EB6C5C7433]@0xffffff7f99419000
            dependency: com.apple.iokit.IOReportFamily(31)[C89107EE-2DF2-3BC3-9F6D-3133D43ED7EF]@0xffffff7f98baf000
            dependency: com.apple.AppleGraphicsDeviceControl(3.12.6)[F211EB28-182A-34BB-A610-87667618F925]@0xffffff7f99493000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[172C2960-EDF5-382D-80A5-C13E97D74880]@0xffffff7f9822b000

BSD process name corresponding to current thread: WindowServer
Boot args: kext-dev-mode=1 dart=0 -gux_defer_usb2 nv_disable=1 rootless=0

Mac OS version:
15E65

##
