### ISSUE TITLE
 请问mac系统下，触控板可以禁用吗？

### ISSUE THREAD

**Issue by diggerdu** [shmilee/T450-Hackintosh#12]
我在bios里面disable 了 trackpad也不起作用

**Comment by shmilee** [comment]
可以。用 RehabMan 的 OS-X-Voodoo-PS2-Controller v1.7.8 之后的版本，安装 VoodooPS2Daemon 。
详细信息看他项目的Change Log：

> 2013-01-24 v1.7.8 (beta)
> - Implemented support for System Preferences -> Accessibility -> "Ignore built-in trackpad when mouse or wireless trackpad is present" If set, the trackpad will be disabled when there is one or more USB mice plugged in. You must install the VoodooPS2Daemon as described in the installation instructions for this to work. This is also implemented for VoodooPS2Mouse.kext if ActLikeTrackpad is set.

安装之后，勾选 System Preferences -> Accessibility -> "Ignore built-in trackpad when mouse or wireless trackpad is present"
下图黑线那里。
![2016-04-28 2 49 19](https://cloud.githubusercontent.com/assets/2681740/14886255/7308cff6-0d82-11e6-9a73-e0ad048e7207.png)

这里只有 VoodooPS2Controller_X1Carbon.kext.zip，搭配 RehabMan 的VoodooPS2Daemon应该可以工作（~~版本不要差太多~~）。毕竟VoodooPS2Controller_X1Carbon.kext只是加了3键的支持。

**Comment by diggerdu** [comment]
太感谢了，这种事应该我自己多Google的
