### ISSUE TITLE
升级BIOS与系统版本遇到问题了

### ISSUE THREAD

**Issue by beordle** [shmilee/T450-Hackintosh#13]
我目前是BIOS 1.19版本。这样UEFI信息就不通用了。我自己了补丁一下。发现其他都完美了就是休眠不成功。系统是10.11.3。不太确定是BIOS的升级还是系统的升级导致的问题。现在shmilee所使用的版本配比是什么。实在不行的话我降级一下BIOS。应该就over了。

休眠的具体状态是我可以进入电源灯一闪闪的状态。但是无法唤醒。我尝试修改了一天DSDT但是不成功。所以特来咨询下。感觉像是补丁*WAK的问题。

**Comment by shmilee** [comment]
有可能是这个补丁`2_usb_prw.txt`不合适，简化的太严重，重新用 RehabMan的 `usb_prw_0x6d_xhc.txt`试试。
另外，我现在bios还是1.18，系统是10.11.5
