### ISSUE TITLE
Clover引导正常 启动安装没反应

### ISSUE THREAD

**Issue by hardbone12** [shmilee/T450-Hackintosh#14]
我是用U盘制作的 启动一切正常 安装的时候图形界面卡在白苹果界面 没有loading条 Verbose模式也没报错 卡在一行+号就不动了  请教是什么原因？

**Comment by transtone** [comment]
卡在+号一般是文件系统的驱动问题，OsxAptioFixDrv-64.efi/OsxAptioDrv-64.efi，VBoxHfs-64.efi/Hfs+.efi 等相同功能的驱动来回调换一下试试。

**Comment by OlingCat** [comment]
请问题主解决了么？怎么解决的？

**Comment by hardbone12** [comment]
换Clover版本 @OlingCat
