### ISSUE TITLE
内置无线网卡能更换么？

### ISSUE THREAD

**Issue by shiweifu** [shmilee/T450-Hackintosh#15]
查到不需要白名单，但是似乎还是得刷 BIOS 才能换？
目前在用 usb 网卡？

**Comment by shmilee** [comment]
可以更换，github.com/polarlights/T450s-Hacktonish，github.com/stevenmirabito/T450s-Hackintosh，他们都换过，刷BIOS免不了。

我现在是用的usb网卡

**Comment by transtone** [comment]
X250/X1C-2015 都已经没有无线网卡的白名单限制了，同一年的产品T450应该也不用刷BIOS才对。
http://forum.51nb.com/thread-1704574-1-1.html

**Comment by shiweifu** [comment]
我入手了 T460P，安装了 OSX 10.11.6，无线网卡换了就驱动了（DW1560），但似乎有点不兼容，睡眠一睡不醒。
不知道联想版的 BCM94352Z 有没有这个问题。

@shmilee  可以考虑换下试试

**Comment by shmilee** [comment]
谢谢 @transtone @shiweifu ，我有时间试试。机器还没拆过，准备和加ssd一起。

**Comment by transtone** [comment]
@shiweifu  我的 x1c-2015 换的 DW1560，除了蓝牙不能用(能识别能配对)之外，暂未发现其他异常，睡眠也没发现太多问题。也出现过一睡不醒的情况，但这个在没换wifi之前也会出现。你的睡眠问题是不是跟电源驱动有关系？

**Comment by shiweifu** [comment]
@transtone 
用 USB 无线网卡一切正常的  - -

**Comment by transtone** [comment]
@shiweifu  https://github.com/jcsnider/X1C-G3-DSDT-Patch/commit/cc09d049e64d6bfb21dd0e649f3bcf373c5ec401
节能管理里的 `唤醒以供网络访问` 是否开启？请关掉。

**Comment by shiweifu** [comment]
@transtone 
关掉了，一样，应该是得改DSDT，然而并不会

**Comment by transtone** [comment]
换了网卡之后，发现耗电量明显比usb网卡大了，不知为何。

**Comment by pan003** [comment]
各位T450有白名单限制吗？有换无线网卡成功的吗？

**Comment by caiking** [comment]
@shiweifu t460p换无线网卡要刷白名单嘛
