### ISSUE TITLE
T450 蓝牙问题

### ISSUE THREAD

**Issue by polarlights** [shmilee/T450-Hackintosh#2]
1. T450是否有蓝牙？
2. 蓝牙如果有，连接蓝牙耳机是否有声音？
   谢谢

**Comment by shmilee** [comment]
蓝牙有的，只传输过文件，没有蓝牙耳机，所以不清楚。

**Comment by polarlights** [comment]
我自带的7265之前也可以发现蓝牙，但是无法发送文件、耳机连上无声，很卡。 现在买了94352Z竟然还是这个样子。真心心里不舒服。Orz

**Comment by polarlights** [comment]
已解决。 蓝牙、无线都可以用了。谢谢
