### ISSUE TITLE
clover加载到+++++++++++++处重启

### ISSUE THREAD

**Issue by shmilee** [shmilee/T450-Hackintosh#3]
屏幕显示：
OsxAptioFixDrv: Starting overrides for .IABootFiles\boot.efi
Using reloc block: Yes, hibernate wake: no
++++++++++++++++++++++++++++++++++++++++++++++

之后黑屏，重启。

遇到两次，都与电源管理相关。
1.  原因在此：http://www.tonymacx86.com/el-capitan-laptop-support/176423-important-10-11-1-update-requires-clover-v3292-later.html
   
    解决方法，升级 Clover ，版本至少是 v3292 。
2. 原因：T450 内置电池，拆机时停用过；重新开机后，外置电池拆下先不用，之后又启用；重新设置内置电池充电阈值。经过以上三步，猜测某一步导致在clover的启动过程中电源管理出了差错。
   
   解决办法：BIOS中，再次停用内置电池，然后插电源线开机。问题得到解决。

**Comment by CS6** [comment]
我也遇到了此問題，無法解决。
