### ISSUE TITLE
Patched AppleHDA + CodecCommander Sleep Problem about device auto-switch

### ISSUE THREAD

**Issue by shmilee** [shmilee/T450-Hackintosh#5]
With Patched AppleHDA +and CodecCommander, Headphone(H) and internal speaker(S) work well before sleep. There is no static noise on headphone.

| plug (H) | status | then pull out (H) | then plug (H) |
| :-: | --- | --- | --- |
| Yes | (H) works, (S) no sound | (S) works, (H) no sound | XXXX |
| No | (S) works, (H) no sound | XXXX | (H) works, (S) no sound |

But, after wake up, the audio can't switch between the Headphone(H) and internal speaker(S). 

| plug (H) before sleep | status Before Sleep | status After wakeup | pull out (H) After wakeup | plug (H) After wakeup |
| :-: | --- | --- | --- | --- |
| Yes | (H) works, (S) has no sound | (H) works, (S) no sound | Still (H) but no sound , (S) no sound | XXXX |
| No | (S) works, (H) no sound | (S) works, (H) no sound | XXXX | Still (S) but no sound , (H) has no sound |

TODO
1. [x] check the verbs and pathmap.
2. [x] edit settings of CodecCommander.
3. [ ] check CC command for mic int, mic ext

**Comment by shmilee** [comment]
TODO
1. check the verbs and pathmap.
2. edit settings of CodecCommander.

**Comment by polarlights** [comment]
The VoodooHDA works great. Why do you want to patch the AppleHDA.kext? It takes a lot of time. XD

**Comment by shmilee** [comment]
@polarlights Just have a try.

**Comment by shmilee** [comment]
TODO
- check CC command for mic int, mic ext

**Comment by stevenmirabito** [comment]
I can confirm that I also have this issue on my T450s running the same patched AppleHDA

**Comment by kimip** [comment]
hello shmilee
first thank you for sharing your work. i have use your alc3232 patch on my thinkpad x1 carbon 2014, speaker, hdmi audio, dp audio work. only headphone port not work. i have read your readme many time but i dont understand. 
[verbs.txt](https://github.com/shmilee/T450-Hackintosh/files/269137/verbs.txt)
[verbitdebug.txt](https://github.com/shmilee/T450-Hackintosh/files/269139/verbitdebug.txt)
i have dump my alc292/alc3232 from linux. and i can see the headphone code is different. but i dont konw how to fix it, i hope you can give some advise.
thank you
kim

**Comment by shmilee** [comment]
How  to fix Verbs?
Read   [reference1](http://www.insanelymac.com/forum/topic/295001-guide-to-patch-applehda-for-your-codec/), [reference2](http://forum.osxlatitude.com/index.php?/topic/1946-complete-applehda-patching-guide/).
And  I recommend high-definition-audio-specification.pdf to you. Look at **7.3.3.31 Configuration Default**, **7.3.3.13 Pin Widget Control**, **Table 141 Required Support for Verbs** and so on.

**Comment by kimip** [comment]
thank you for reply. after reading your reference i found my x1 code is same as yours. After all it was the microphone setting in Bios. After i enable it, i have headphone sound. thank you.

**Comment by kimip** [comment]
i found  AppleHDA + CodecCommander + VoodooHDA-287.kext 
and change ConfigData to
<01271c00 01271d00 01271ea6 01271f99 01471c10 01471d00 01471e17 01471f99 01571c20 01571d10 01571e21 01571f01 01a71c30 01a71d10 01a71e81 01a71f01>
sound work after sleep speak+headphone+hdwi+displayport+autodetect

**Comment by stevenmirabito** [comment]
@kimip Could you provide a little more detail on how you got it working? Are you using a combination of AppleHDA and VoodooHDA? Did you have to change the AppleHDA patch in this repo?

**Comment by kimip** [comment]
yes. add voodoohda.kext  and patch the applehda with the code above.

**Comment by transtone** [comment]
@kimip  Could you please share your patched drivers?
