### ISSUE TITLE
VoodooPS2Controller_X1Carbon.kext trackpoint buttons usability

### ISSUE THREAD

**Issue by spamoco** [shmilee/T450-Hackintosh#7]
Hi Shmilee,
you're doin a really great job here...  I was be able to start osx with my T450s (I'm learning from your work and other resources).

The biggest issue apart from WIFI/Bluetooth module (I'm waiting for it) is a weak support of trackpoint buttons - in my model, when you press left button and hold it probably causes number of click events, so no dragging is possible.

Do you have similar findings? Are there any settings to "tweak" etc.?

**Comment by shmilee** [comment]
Try to hold left button, and use trackpoint to drag. (use trackpoint + buttons together, or just use trackpad only)
And here is a similar issue: https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/65
Or this https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/29

A few days ago, I opened Issue #6, tried to do sth. But it's beyond my capability.

About WIFI/Bluetooth, you need to remove the whitelist from bios, and buy a BCM94352z. See #2, and his repository polarlights/T450s-Hacktonish. I don't want to change my BIOS, so haven't done that.

**Comment by spamoco** [comment]
Thanks for the answer. 

I thought that Lenovo in T450 series has removed the WIFI whitelist from the bios... anyway, I will explore polarlights repo, maybe something will come up :)

**Comment by shmilee** [comment]
Close this.  About whitelist, you can see here #10
