### ISSUE TITLE
希望您看得懂中文，我您修改CLOVER的教學上有些疑問

### ISSUE THREAD

**Issue by CS6** [shmilee/T450-Hackintosh#8]
希望您看得懂中文，我在您修改CLOVER的教學上有些疑問
(我是看主業的教程Install Clover)，
我有一台T450 940m版本的Thinkpad(i5 5200u/ intel7265 )，
我想安裝OSX 10.11 ，
原本用CLOVER但是出了一些問題，所以改用您的教學
可是我在Arch Linux的部分遇到了部分困難，
想請問是否可以有其他方法，例如用Federa,OSX,Ubunt之類的系統，
小弟不才如有冒犯請見諒，十分感謝>

**Comment by shmilee** [comment]
Fedora等Linux发行版都可以，windows也可以。
这是手动安装clover，首先你要挂载EFI分区，然后把CLover的ISO内 EFI/CLOVER/ 下的文件复制到EFI分区 EFI/Clover/下。不同的linux发行版，都有那些mount，cp，mv等基本命令。windows也有挂载EFI分区的方法。
另外，我安装时，只复制了需要的文件，可能也给你造成困惑了。

你一开始对clover可能不熟悉，我的建议是最好先看看[这里](http://clover-wiki.zetam.org/Home)。里面有你需要的基础知识。不同的安装方法，你可以都了解一下，选择适合自己的，不一定非要用Linux。

**Comment by CS6** [comment]
好的，我在嘗試一段時間，

**Comment by CS6** [comment]
不好意思我又來打擾了，關於Install Image部分，是否使用linux?還是要用mac(我目前使用ubuntu，但是無法掛載InstallESD.dmg，我也嘗試過acetoneios不知道我是否理解錯了甚麼?

**Comment by shmilee** [comment]
我写的过程，是在mac下的。所以需要找个有mac的朋友，一开始还要一个8G的优盘。
linux下不知道有没有方法。
win下，需要一个名为transmac的软件，并且下载的镜像应该也不一样。win下我也不清楚，只知道这些。这里有win下的方法：http://bbs.pcbeta.com/viewthread-1417529-1-1.html

**Comment by CS6** [comment]
InstallESD.dmg為唯讀，無法複製到HFS+的U盤，我在嘗試直接用蘋果來分割系統碟(以上的過程我是在UBUNTU完成的)
