### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by ghost** [shmilee/T450-Hackintosh#9]
Hey thanks for all your work with this laptop. It benefited me so much! Anyways, my sleep doesn't work. When I sleep, it goes to sleep fine, but then it will not wake up from sleep. Pressing the power buttons, the keyboard, the mouse all do not work to wake up the laptop. Do you have the same problem?

**Comment by shmilee** [comment]
No. My T450 can wake up from sleep, when power button or Fn is pressed, or open the lid.  Keyboard and USB devices do not work to do that. 
I think you need some DSDT patches. What have you done with DSDT?

**Comment by ghost** [comment]
I have done the patches you recommended and fixed it for HDMI audio but that's it.
[DSDT.aml.zip](https://github.com/shmilee/T450-Hackintosh/files/86401/DSDT.aml.zip)

Could you attach your patched one for me to see if it would work. Also, I do not get how to use the USB Injector. Could you attach the made kext, I keep getting errors when trying to make the kext from scratch.

**Comment by shmilee** [comment]
Where did  you get you DSDT tables? Maybe linux is a better choice. And in this repo, you can get the patched DSDT by running `auto_patch.sh` in DSDT directory.  Anyway, this is the one I am using.
[patched_DSDT.zip](https://github.com/shmilee/T450-Hackintosh/files/88379/patched_DSDT.zip)

Here is the USB Injector
[USB_Injector_T450.kext.zip](https://github.com/shmilee/T450-Hackintosh/files/88383/USB_Injector_T450.kext.zip)

**Comment by ghost** [comment]
Same thing with your DSDT. Also, the USB Injector doesn't work (my Webcam and Bluetooth Don't work). Do I need custom values for it?

**Comment by shmilee** [comment]
Sleep: Check the [bios setting，part＃1](http://www.tonymacx86.com/yosemite-laptop-guides/162391-guide-2015-x1-carbon-yosemite.html) ，Security > FingerPrint > Set Predesktop Authentication to Disabled.

USB: check the port values by aida64 in windows. Or use IORegistryExplorer in yosemite.

**Comment by ghost** [comment]
Still no luck with sleep

**Comment by shmilee** [comment]
~~Have you try to get your DSDT from linux, and run `auto_patch.sh` in Mac OS X? ~~

**Comment by ghost** [comment]
Yea I tried that

**Comment by ghost** [comment]
Okay got it I changed something in my BIOS and it works now

**Comment by febriyan1302** [comment]
Hi vampi369325, what your change in bios ? i disable fingerprint, sleep OK, but no response if i pressed fn or power button to wake up laptop.
